//! Integration tests for the 7z archive using real fixtures in `testdata/7z/`
//! (generated by testdata/gen/gen-7z.sh, p7zip 17.06).
//!
//! Coverage: LZMA2 (solid + non-solid), ZSTD method, AES-256 (header and
//! content encryption), nested archives, corrupt input, and registry
//! auto-detection.

use std::io::Read;
use std::path::{Path, PathBuf};

use hajizip_core::archive::sevenz::SevenZipFormat;
use hajizip_core::registry::Registry;
use hajizip_core::source::Source;
use hajizip_core::{Archive, EntryPath, NodeKind, OpenOptions, Secret};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/7z")
        .canonicalize()
        .expect("testdata/7z must exist (run testdata/gen/gen-7z.sh)")
}

fn fixture(name: &str) -> PathBuf {
    fixture_dir().join(name)
}

fn registry() -> Registry {
    Registry::new().register_archive(SevenZipFormat)
}

fn open(name: &str) -> hajizip_core::Result<Box<dyn Archive>> {
    registry().open_archive(Source::Path(fixture(name)), &OpenOptions::default())
}

/// The error of an open that is expected to fail.
fn open_err(name: &str) -> hajizip_core::Error {
    open(name)
        .err()
        .unwrap_or_else(|| panic!("{name} unexpectedly opened"))
}

fn open_with_password(name: &str, password: &str) -> hajizip_core::Result<Box<dyn Archive>> {
    let opts = OpenOptions {
        password: Some(Secret::new(password)),
        ..Default::default()
    };
    registry().open_archive(Source::Path(fixture(name)), &opts)
}

fn read_entry(archive: &dyn Archive, path: &str) -> hajizip_core::Result<Vec<u8>> {
    let entries = archive.entries()?;
    let entry = entries
        .iter()
        .find(|e| e.path.as_str() == path)
        .expect("entry present");
    let mut reader = archive.reader(entry)?;
    let mut buf = Vec::new();
    reader.read_to_end(&mut buf)?;
    Ok(buf)
}

fn entry_paths(archive: &dyn Archive) -> Vec<String> {
    let mut paths: Vec<String> = archive
        .entries()
        .expect("listing works")
        .into_iter()
        .map(|e| e.path.as_str().to_owned())
        .collect();
    paths.sort();
    paths
}

const BASIC_PATHS: [&str; 3] = ["a.txt", "dir", "dir/b.txt"];

fn assert_basic(archive: &dyn Archive) {
    assert_eq!(entry_paths(archive), BASIC_PATHS);
    assert_eq!(
        read_entry(archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
    assert_eq!(
        read_entry(archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
}

#[test]
fn basic_lzma2_lists_and_reads() {
    let archive = open("basic.7z").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn solid_archive_reports_sequential_access() {
    // p7zip defaults to solid; single-entry reads decode the whole block.
    let archive = open("basic.7z").expect("opens");
    assert!(!archive.capabilities().random_access);
}

#[test]
fn nonsolid_archive_reports_random_access() {
    let archive = open("nonsolid.7z").expect("opens");
    assert_basic(&*archive);
    assert!(archive.capabilities().random_access);
}

#[test]
fn zstd_method_decodes() {
    // `-m0=zstd` (7-Zip ZS codec 0x4F71101): decodes through the zstd feature.
    let archive = open("zstd.7z").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn node_lookup_and_kind() {
    let archive = open("basic.7z").expect("opens");
    let entries = archive.entries().expect("lists");
    let dir = entries
        .iter()
        .find(|e| e.path.as_str() == "dir")
        .expect("dir entry");
    assert_eq!(dir.kind, NodeKind::Dir);
    let node = archive
        .node(&EntryPath::new("dir/b.txt").expect("valid"))
        .expect("node found");
    assert_eq!(node.kind(), NodeKind::File);
    let mut buf = Vec::new();
    node.reader()
        .expect("reads")
        .read_to_end(&mut buf)
        .expect("reads");
    assert_eq!(buf, b"nested content\n");
}

#[test]
fn extract_to_matches_reader() {
    let archive = open("basic.7z").expect("opens");
    let entries = archive.entries().expect("lists");
    let a = entries.iter().find(|e| e.path.as_str() == "a.txt").unwrap();
    let mut sink = Vec::new();
    let n = archive.extract_to(a, &mut sink).expect("extracts");
    assert_eq!(n as usize, sink.len());
    assert_eq!(sink, b"Hello, hajizip!\n");
}

#[test]
fn metadata_sizes_and_crc() {
    let archive = open("basic.7z").expect("opens");
    let entries = archive.entries().expect("lists");
    let a = entries
        .iter()
        .find(|e| e.path.as_str() == "a.txt")
        .expect("entry");
    assert_eq!(a.uncompressed_size, Some(16));
    assert!(a.crc.is_some(), "7z stores per-file CRC");
    let dir = entries.iter().find(|e| e.path.as_str() == "dir").unwrap();
    assert_eq!(dir.uncompressed_size, None);
}

#[test]
fn wrong_password_errors_on_read() {
    // The header is plain (only content is encrypted), so opening with a
    // wrong password succeeds; the password is checked when content decodes.
    let archive = open_with_password("enc-content.7z", "nope").expect("opens");
    let entries = archive.entries().expect("lists");
    let a = entries.iter().find(|e| e.path.as_str() == "a.txt").unwrap();
    let err = archive.reader(a).err().expect("wrong password must fail");
    assert!(matches!(err, hajizip_core::Error::WrongPassword));
}

#[test]
fn content_encryption_requires_password() {
    // Plain header, AES-256 content: opens without a password...
    let archive = open("enc-content.7z").expect("opens");
    let caps = archive.capabilities();
    assert!(caps.encrypted);
    assert!(caps.needs_password);
    // ...but reading an entry reports PasswordRequired...
    let entries = archive.entries().expect("lists");
    let a = entries.iter().find(|e| e.path.as_str() == "a.txt").unwrap();
    let err = archive.reader(a).err().expect("encrypted entry must fail");
    assert!(matches!(err, hajizip_core::Error::PasswordRequired));
    // ...and with the right password everything decodes.
    let archive = open_with_password("enc-content.7z", "secret").expect("opens with password");
    assert_basic(&*archive);
}

#[test]
fn encrypted_header_requires_password_on_open() {
    let err = open_err("enc.7z");
    assert!(matches!(err, hajizip_core::Error::PasswordRequired));
    let archive = open_with_password("enc.7z", "secret").expect("opens with password");
    assert_basic(&*archive);
}

#[test]
fn nested_archives_open() {
    let archive = open("nested.7z").expect("opens");
    let paths = entry_paths(&*archive);
    assert_eq!(
        paths,
        ["inner.7z", "inner.tar.gz", "inner.tar.xz", "inner.zip"]
    );
    let entries = archive.entries().expect("lists");
    for name in ["inner.7z", "inner.tar.gz", "inner.tar.xz", "inner.zip"] {
        let entry = entries
            .iter()
            .find(|e| e.path.as_str() == name)
            .expect("entry");
        // nested.7z is generated non-solid so entries are sniffed at open.
        assert_eq!(entry.kind, NodeKind::Archive, "{name}");
        let nested = archive
            .open_nested(entry, &OpenOptions::default())
            .unwrap_or_else(|e| panic!("open nested {name}: {e}"));
        let inner_paths = entry_paths(&*nested);
        assert_eq!(inner_paths, BASIC_PATHS, "inner {name}");
        let mut buf = Vec::new();
        nested
            .reader(
                &nested
                    .entries()
                    .expect("lists")
                    .into_iter()
                    .find(|e| e.path.as_str() == "a.txt")
                    .expect("a.txt"),
            )
            .expect("reads")
            .read_to_end(&mut buf)
            .expect("reads");
        assert_eq!(buf, b"Hello, hajizip!\n", "inner {name}");
    }
}

#[test]
fn corrupt_header_errors() {
    let err = open_err("corrupt.7z");
    assert!(matches!(
        err,
        hajizip_core::Error::Io(_) | hajizip_core::Error::CorruptArchive(_)
    ));
}

#[test]
fn detects_by_magic_via_registry() {
    let reg = registry();
    let fmt = reg
        .detect_archive(b"7z\xbc\xaf\x27\x1c", None)
        .expect("detected");
    assert_eq!(fmt.id(), "7z");
    let fmt = reg.detect_archive(b"junk", Some("7z")).expect("by ext");
    assert_eq!(fmt.id(), "7z");
    // gzip magic must not be claimed by the 7z format.
    assert!(reg.detect_archive(b"\x1f\x8b\x08", None).is_none());
}
