//! Integration tests for the tar archive (and tar.gz chaining) using real
//! fixtures in `testdata/tar/` (generated by testdata/gen/gen-tar.sh).

use std::io::Read;
use std::path::{Path, PathBuf};

use hajizip_core::archive::tar::TarFormat;
use hajizip_core::codec::gzip::GzipFormat;
use hajizip_core::codec::xz::XzFormat;
use hajizip_core::registry::Registry;
use hajizip_core::source::Source;
use hajizip_core::{Archive, EntryPath, NodeKind, OpenOptions};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/tar")
        .canonicalize()
        .expect("testdata/tar must exist (run testdata/gen/gen-tar.sh)")
}

fn fixture(name: &str) -> PathBuf {
    fixture_dir().join(name)
}

/// A registry with the tar archive and gzip/xz codecs registered.
fn registry() -> Registry {
    Registry::new()
        .register_archive(TarFormat)
        .register_codec(GzipFormat)
        .register_codec(XzFormat)
}

/// Open a fixture through the registry (auto-detect, incl. tar.gz chaining).
fn open(name: &str) -> hajizip_core::Result<Box<dyn Archive>> {
    registry().open_archive(Source::Path(fixture(name)), &OpenOptions::default())
}

fn read_entry(archive: &dyn Archive, path: &str) -> hajizip_core::Result<Vec<u8>> {
    let entries = archive.entries()?;
    let entry = entries
        .iter()
        .find(|e| e.path.as_str() == path)
        .expect("entry present");
    let mut reader = archive.reader(entry)?;
    let mut buf = Vec::new();
    reader.read_to_end(&mut buf)?;
    Ok(buf)
}

fn entry_paths(archive: &dyn Archive) -> Vec<String> {
    archive
        .entries()
        .expect("listing works")
        .into_iter()
        .map(|e| e.path.as_str().to_owned())
        .collect()
}

const BASIC_PATHS: [&str; 3] = ["a.txt", "dir", "dir/b.txt"];

fn assert_basic(archive: &dyn Archive) {
    let mut paths = entry_paths(archive);
    paths.sort();
    assert_eq!(paths, BASIC_PATHS);
    assert_eq!(
        read_entry(archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
    assert_eq!(
        read_entry(archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
}

#[test]
fn plain_tar_lists_and_reads() {
    let archive = open("basic.tar").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn tar_gz_opens_through_registry_chaining() {
    let archive = open("basic.tar.gz").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn tgz_opens_by_content_magic() {
    // `.tgz` bytes are gzip; the extension is never used as a tar hint when
    // the head signals compression.
    let archive = open("hello.tgz").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn tar_xz_opens_through_registry_chaining() {
    let archive = open("basic.tar.xz").expect("opens");
    assert_basic(&*archive);
}

#[test]
fn random_access_reads_in_any_order() {
    let archive = open("basic.tar").expect("opens");
    assert_eq!(
        read_entry(&*archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
    assert_eq!(
        read_entry(&*archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
    assert_eq!(
        read_entry(&*archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
}

#[test]
fn long_names_list() {
    let archive = open("long.tar").expect("opens");
    let paths = entry_paths(&*archive);
    assert_eq!(paths.len(), 1, "got {paths:?}");
    // deep/ + 60 x + / + 50 y + .txt = 5+60+1+50+4 = 120 chars > 100.
    assert_eq!(paths[0].len(), 120, "got {:?}", paths[0]);
    assert!(paths[0].starts_with("deep/"));
}

#[test]
fn symlink_entry_has_symlink_kind() {
    let archive = open("sym.tar").expect("opens");
    let entries = archive.entries().expect("listing works");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].kind, NodeKind::Symlink);
    assert_eq!(entries[0].path.as_str(), "link");
}

#[test]
fn absolute_path_is_normalized_to_relative() {
    let archive = open("abs.tar").expect("opens");
    let entries = archive.entries().expect("listing works");
    assert_eq!(entries.len(), 1);
    // EntryPath strips the leading `/`; the raw bytes are preserved.
    assert!(!entries[0].path.as_str().starts_with('/'));
    assert!(entries[0].raw_name.starts_with(b"/"));
}

#[test]
fn traversal_entry_is_skipped_at_listing() {
    let archive = open("slip.tar").expect("opens");
    let paths = entry_paths(&*archive);
    assert!(paths.is_empty(), "got {paths:?}");
}

#[test]
fn nested_archives_open_through_open_nested() {
    let archive = open("nested.tar").expect("opens");
    let opts = OpenOptions::default();
    let mut paths = entry_paths(&*archive);
    paths.sort();
    assert_eq!(paths, ["inner.tar", "inner.tar.gz", "inner.zip"]);

    for (name, archive) in archive
        .entries()
        .expect("listing works")
        .into_iter()
        .map(|e| {
            (
                e.path.as_str().to_owned(),
                archive.open_nested(&e, &opts).expect("nested opens"),
            )
        })
    {
        assert_basic(&*archive);
        std::mem::drop(name);
    }
}

#[test]
fn empty_tar_has_no_entries() {
    let archive = open("empty.tar").expect("opens");
    assert!(archive.entries().expect("listing works").is_empty());
}

#[test]
fn many_entries_list_completely() {
    let archive = open("many.tar").expect("opens");
    assert_eq!(archive.entries().expect("listing works").len(), 10_000);
}

#[test]
fn extract_to_writes_bytes() {
    let archive = open("basic.tar").expect("opens");
    let entry = archive
        .entries()
        .expect("listing works")
        .into_iter()
        .find(|e| e.path.as_str() == "a.txt")
        .unwrap();
    let mut sink = Vec::new();
    let n = archive.extract_to(&entry, &mut sink).expect("extracts");
    assert_eq!(n, 16);
    assert_eq!(sink, b"Hello, hajizip!\n");
}

#[test]
fn node_lookup_and_tree() {
    let archive = open("basic.tar").expect("opens");
    let node = archive
        .node(&EntryPath::new("dir").expect("valid"))
        .expect("dir found");
    assert_eq!(node.kind(), NodeKind::Dir);
    let children = node.children().expect("children");
    assert_eq!(children.len(), 1);
    assert_eq!(children[0].meta().path.as_str(), "dir/b.txt");

    let root = archive.root().expect("root");
    let root_children = root.children().expect("children");
    assert_eq!(root_children.len(), 2);
    assert_eq!(root_children[0].meta().path.as_str(), "dir"); // dirs first
    assert_eq!(root_children[1].meta().path.as_str(), "a.txt");

    assert!(
        archive
            .node(&EntryPath::new("missing").expect("valid"))
            .is_err()
    );
}

#[test]
fn registry_detection_magic_first_then_extension() {
    let reg = Registry::new().register_archive(TarFormat);
    let mut head = [0u8; 512];
    head[257..262].copy_from_slice(b"ustar");
    assert!(reg.detect_archive(&head, None).is_some());
    assert!(reg.detect_archive(b"junk", Some("tar")).is_some());
    assert!(reg.detect_archive(b"junk", None).is_none());
    // A gzip head with a .tgz extension must NOT match tar (bytes are gzip).
    let reg = Registry::new()
        .register_archive(TarFormat)
        .register_codec(GzipFormat);
    assert!(reg.detect_archive(b"\x1f\x8b...", Some("tgz")).is_none());
    assert!(reg.detect_archive(b"\x1f\x8b...", None).is_none());
    // ... but opening it works through the codec chain.
    let archive = reg
        .open_archive(Source::Path(fixture("hello.tgz")), &OpenOptions::default())
        .expect("chained open");
    assert_basic(&*archive);
}

#[test]
fn zip_bytes_are_not_misdetected_as_tar() {
    let reg = Registry::new()
        .register_archive(TarFormat)
        .register_codec(GzipFormat);
    // A zip file has neither tar magic nor a compressed signature: opening it
    // must fail cleanly (no zip format registered here).
    let zip_bytes = std::fs::read(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../testdata/zip/basic.zip")
            .canonicalize()
            .expect("zip fixture exists"),
    )
    .expect("readable");
    assert!(
        reg.detect_archive(&zip_bytes[..zip_bytes.len().min(512)], None)
            .is_none()
    );
    match reg.open_archive(Source::Memory(zip_bytes), &OpenOptions::default()) {
        Err(hajizip_core::error::Error::UnsupportedFormat(_)) => {}
        Ok(_) => panic!("expected UnsupportedFormat, got Ok"),
        Err(e) => panic!("expected UnsupportedFormat, got {e}"),
    }
}
