//! Integration tests for the xz codec using real fixtures in `testdata/xz/`
//! (generated by testdata/gen/gen-xz.sh, xz 5.8.3).

use std::io::Read;
use std::path::{Path, PathBuf};

use hajizip_core::Codec;
use hajizip_core::codec::xz::{XzCodec, XzFormat};
use hajizip_core::registry::Registry;

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/xz")
        .canonicalize()
        .expect("testdata/xz must exist (run testdata/gen/gen-xz.sh)")
}

fn fixture(name: &str) -> PathBuf {
    fixture_dir().join(name)
}

fn decode_file(name: &str) -> hajizip_core::Result<Vec<u8>> {
    let bytes = std::fs::read(fixture(name)).expect("fixture readable");
    let codec = XzCodec;
    let mut reader = codec.decompress(Box::new(bytes.as_slice()))?;
    let mut out = Vec::new();
    reader.read_to_end(&mut out)?;
    Ok(out)
}

const HELLO: &[u8] = b"Hello, hajizip!\n";

#[test]
fn decodes_hello_xz() {
    assert_eq!(decode_file("hello.txt.xz").expect("decodes"), HELLO);
}

#[test]
fn decodes_concatenated_streams_fixture() {
    // Two concatenated xz streams of the same content.
    assert_eq!(
        decode_file("multi-stream.xz").expect("decodes"),
        [HELLO, HELLO].concat()
    );
}

#[test]
fn truncated_stream_errors() {
    assert!(decode_file("corrupt-truncated.xz").is_err());
}

#[test]
fn flipped_payload_errors() {
    assert!(decode_file("corrupt-flip.xz").is_err());
}

#[test]
fn detected_and_openable_via_registry_as_codec() {
    let reg = Registry::new().register_codec(XzFormat);
    // The registry treats a standalone codec stream as unsupported for
    // `open_archive` (it is not an archive), but the codec must be detected.
    let fmt = reg
        .detect_codec(&[0xfd, b'7', b'z', b'X', b'Z', 0x00], None)
        .expect("detected by magic");
    assert_eq!(fmt.id(), "xz");
}
