//! Integration tests for the zip archive using real fixtures in
//! `testdata/zip/` (generated by testdata/gen/gen-zip.sh, Info-ZIP zip 3.0).

use std::io::Read;
use std::path::{Path, PathBuf};

use hajizip_core::archive::zip::ZipFormat;
use hajizip_core::registry::Registry;
use hajizip_core::source::Source;
use hajizip_core::{Archive, EntryPath, NodeKind, OpenOptions};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/zip")
        .canonicalize()
        .expect("testdata/zip must exist (run testdata/gen/gen-zip.sh)")
}

fn fixture(name: &str) -> PathBuf {
    fixture_dir().join(name)
}

/// Open a fixture through a registry with the zip format registered.
fn open(name: &str) -> hajizip_core::Result<Box<dyn Archive>> {
    let reg = Registry::new().register_archive(ZipFormat);
    reg.open_archive(Source::Path(fixture(name)), &OpenOptions::default())
}

/// Locate an entry by path and read its decompressed bytes.
fn read_entry(archive: &dyn Archive, path: &str) -> hajizip_core::Result<Vec<u8>> {
    let entries = archive.entries()?;
    let entry = entries
        .iter()
        .find(|e| e.path.as_str() == path)
        .expect("entry present");
    let mut reader = archive.reader(entry)?;
    let mut buf = Vec::new();
    reader.read_to_end(&mut buf)?;
    Ok(buf)
}

fn entry_paths(archive: &dyn Archive) -> Vec<String> {
    archive
        .entries()
        .expect("listing works")
        .into_iter()
        .map(|e| e.path.as_str().to_owned())
        .collect()
}

#[test]
fn basic_lists_entries_with_kinds_and_sizes() {
    let archive = open("basic.zip").expect("opens");
    let mut paths = entry_paths(&*archive);
    paths.sort();
    assert_eq!(paths, ["a.txt", "dir", "dir/b.txt"]);
    let entries = archive.entries().expect("listing works");
    let a = entries.iter().find(|e| e.path.as_str() == "a.txt").unwrap();
    assert_eq!(a.kind, NodeKind::File);
    assert_eq!(a.uncompressed_size, Some(16));
    assert!(!a.encrypted);
    let dir = entries.iter().find(|e| e.path.as_str() == "dir").unwrap();
    assert_eq!(dir.kind, NodeKind::Dir);
    let b = entries
        .iter()
        .find(|e| e.path.as_str() == "dir/b.txt")
        .unwrap();
    assert_eq!(b.kind, NodeKind::File);
    assert_eq!(b.uncompressed_size, Some(15));
}

#[test]
fn basic_content_matches_plaintext() {
    let archive = open("basic.zip").expect("opens");
    assert_eq!(
        read_entry(&*archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
    assert_eq!(
        read_entry(&*archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
}

#[test]
fn random_access_reads_in_any_order() {
    let archive = open("basic.zip").expect("opens");
    // Read a later entry, then an earlier one, then repeat: order must not
    // matter (the shared reader is re-positioned per entry).
    assert_eq!(
        read_entry(&*archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
    assert_eq!(
        read_entry(&*archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
    assert_eq!(
        read_entry(&*archive, "dir/b.txt").expect("reads"),
        b"nested content\n"
    );
}

#[test]
fn stored_entries_read() {
    let archive = open("stored.zip").expect("opens");
    assert_eq!(
        read_entry(&*archive, "a.txt").expect("reads"),
        b"Hello, hajizip!\n"
    );
}

#[test]
fn utf8_names_list() {
    let archive = open("utf8.zip").expect("opens");
    let paths = entry_paths(&*archive);
    assert!(paths.contains(&"你好.txt".to_owned()), "got {paths:?}");
    assert!(paths.contains(&"hello.txt".to_owned()), "got {paths:?}");
}

#[test]
fn gbk_name_falls_back_lossy_but_keeps_raw() {
    let archive = open("gbk.zip").expect("opens");
    let entries = archive.entries().expect("listing works");
    assert_eq!(entries.len(), 1);
    let e = &entries[0];
    // GBK bytes of 你好 (C4 E3 BA C3), EFS unset: not valid UTF-8.
    assert_eq!(e.raw_name, [0xc4, 0xe3, 0xba, 0xc3]);
    // M1 falls back to lossy UTF-8 for display; raw bytes are preserved.
    assert!(e.path.as_str().contains('\u{fffd}'));
    // The content itself is still readable.
    assert_eq!(
        read_entry(&*archive, e.path.as_str()).expect("reads"),
        b"gbk content\n"
    );
}

#[test]
fn zipslip_entry_is_skipped_at_listing() {
    let archive = open("zipslip.zip").expect("opens");
    let paths = entry_paths(&*archive);
    assert!(paths.contains(&"ok.txt".to_owned()));
    // The `../` entry must never appear (EntryPath validation rejects it).
    assert!(!paths.iter().any(|p| p.contains("..")), "got {paths:?}");
}

#[test]
fn encrypted_entry_reports_unsupported_reads() {
    let archive = open("enc.zip").expect("opens");
    let entries = archive.entries().expect("listing works");
    assert_eq!(entries.len(), 1);
    assert!(entries[0].encrypted);
    assert!(archive.capabilities().encrypted);
    let e = &entries[0];
    assert!(matches!(
        archive.reader(e),
        Err(hajizip_core::error::Error::UnsupportedFeature(_))
    ));
    let mut sink = Vec::new();
    assert!(matches!(
        archive.extract_to(e, &mut sink),
        Err(hajizip_core::error::Error::UnsupportedFeature(_))
    ));
}

#[test]
fn nested_zip_opens_through_open_nested() {
    let archive = open("nested.zip").expect("opens");
    let inner = archive
        .open_nested(
            archive
                .entries()
                .expect("listing works")
                .iter()
                .find(|e| e.path.as_str() == "inner.zip")
                .expect("inner.zip present"),
            &OpenOptions::default(),
        )
        .expect("nested zip opens");
    let mut inner_paths = entry_paths(&*inner);
    inner_paths.sort();
    assert_eq!(inner_paths, ["a.txt", "dir", "dir/b.txt"]);
    // The outer file is still readable.
    assert_eq!(read_entry(&*archive, "top.txt").expect("reads"), b"top\n");
}

#[test]
fn corrupt_archive_errors_on_open() {
    match open("corrupt.zip") {
        Err(hajizip_core::error::Error::CorruptArchive(_) | hajizip_core::error::Error::Io(_)) => {}
        Ok(_) => panic!("expected CorruptArchive or Io, got Ok"),
        Err(e) => panic!("expected CorruptArchive or Io, got {e}"),
    }
}

#[test]
fn empty_archive_has_no_entries() {
    let archive = open("empty.zip").expect("opens");
    assert!(archive.entries().expect("listing works").is_empty());
    assert!(archive.capabilities().random_access);
}

#[test]
fn many_entries_list_quickly_and_completely() {
    let archive = open("many.zip").expect("opens");
    assert_eq!(archive.entries().expect("listing works").len(), 10_000);
}

#[test]
fn registry_detects_zip_by_magic_and_extension() {
    let reg = Registry::new().register_archive(ZipFormat);
    assert!(reg.detect_archive(b"PK\x03\x04...", None).is_some());
    assert!(reg.detect_archive(b"PK\x05\x06...", None).is_some());
    assert!(reg.detect_archive(b"not a zip", Some("zip")).is_some());
    assert!(reg.detect_archive(b"not a zip", None).is_none());
    assert!(reg.detect_archive(b"\x1f\x8b...", None).is_none());
}

#[test]
fn node_lookup_and_tree() {
    let archive = open("basic.zip").expect("opens");
    let node = archive
        .node(&EntryPath::new("dir").expect("valid"))
        .expect("dir found");
    assert_eq!(node.kind(), NodeKind::Dir);
    let children = node.children().expect("children");
    let mut child_paths: Vec<String> = children
        .iter()
        .map(|c| c.meta().path.as_str().to_owned())
        .collect();
    child_paths.sort();
    assert_eq!(child_paths, ["dir/b.txt"]);

    let file = archive
        .node(&EntryPath::new("a.txt").expect("valid"))
        .expect("file found");
    assert_eq!(file.kind(), NodeKind::File);
    let mut buf = Vec::new();
    file.reader()
        .expect("reader")
        .read_to_end(&mut buf)
        .expect("reads");
    assert_eq!(buf, b"Hello, hajizip!\n");

    assert!(
        archive
            .node(&EntryPath::new("missing").expect("valid"))
            .is_err()
    );

    // Root children include the dir (dirs first, then alphabetical).
    let root = archive.root().expect("root");
    assert_eq!(root.kind(), NodeKind::Dir);
    let root_children = root.children().expect("children");
    assert_eq!(root_children.len(), 2);
    assert_eq!(root_children[0].meta().path.as_str(), "dir");
    assert_eq!(root_children[1].meta().path.as_str(), "a.txt");
}

#[test]
fn extract_to_writes_bytes() {
    let archive = open("basic.zip").expect("opens");
    let entry = archive
        .entries()
        .expect("listing works")
        .into_iter()
        .find(|e| e.path.as_str() == "a.txt")
        .unwrap();
    let mut sink = Vec::new();
    let n = archive.extract_to(&entry, &mut sink).expect("extracts");
    assert_eq!(n, 16);
    assert_eq!(sink, b"Hello, hajizip!\n");
}

#[test]
fn archive_and_nodes_are_send_sync() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<ZipFormat>();
    // Open an archive to prove the trait-object value is Send + Sync too.
    let archive = open("basic.zip").expect("opens");
    assert_send_sync::<Box<dyn Archive>>();
    std::mem::drop(archive);
}
