//! The GUI's composition root: which formats the application supports.
//!
//! Per `architecture.md` §4.4 and §5.1, the abstract core does not enumerate
//! formats; the application (here, the GUI) references the concrete format
//! implementations it wants and registers them into a [`Registry`]. This is the
//! only place in the GUI that names concrete formats.
//!
//! Core M1 landed the first three formats and they are wired here: ZIP and TAR
//! as direct archives, plus the gzip codec so `.tar.gz` / `.tgz` open through
//! the registry's codec→archive chain. As further formats land (xz, 7z, zstd,
//! ...), add a single `.register_archive(..)` / `.register_codec(..)` line.
//! Formats that are not registered degrade gracefully: opening them yields an
//! "unsupported format" error instead of a crash.

use hajizip_core::Registry;
use hajizip_core::archive::tar::TarFormat;
use hajizip_core::archive::zip::ZipFormat;
use hajizip_core::codec::gzip::GzipFormat;

/// Build the registry of all formats the GUI currently supports.
pub fn compose_registry() -> Registry {
    Registry::new()
        .register_archive(ZipFormat)
        .register_archive(TarFormat)
        .register_codec(GzipFormat)
}

#[cfg(test)]
mod tests {
    use super::*;
    use hajizip_core::{Archive, Error, NodeKind, OpenOptions, Source};
    use std::path::{Path, PathBuf};

    /// Repo-root `testdata/` (generated by `testdata/gen/`), shared with the
    /// core integration tests.
    fn fixture_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../testdata")
            .canonicalize()
            .expect("repo-root testdata/ must exist (generated by testdata/gen)")
    }

    fn fixture(rel: &str) -> PathBuf {
        fixture_dir().join(rel)
    }

    /// Open a fixture through the composed registry (the same path the app
    /// takes at runtime).
    fn open(rel: &str) -> hajizip_core::Result<Box<dyn Archive>> {
        compose_registry().open_archive(Source::Path(fixture(rel)), &OpenOptions::default())
    }

    fn names(archive: &dyn Archive) -> Vec<String> {
        let mut names: Vec<String> = archive
            .entries()
            .unwrap()
            .into_iter()
            .map(|e| e.path.as_str().to_string())
            .collect();
        names.sort();
        names
    }

    #[test]
    fn composed_registry_has_the_three_m1_formats() {
        let reg = compose_registry();
        assert_eq!(reg.archive_formats().len(), 2, "zip + tar");
        assert_eq!(reg.codecs().len(), 1, "gzip");
    }

    #[test]
    fn zip_fixture_opens_and_lists_entries() {
        let archive = open("zip/basic.zip").expect("zip opens via composed registry");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
        let entries = archive.entries().unwrap();
        let dir = entries.iter().find(|e| e.path.as_str() == "dir").unwrap();
        assert_eq!(dir.kind, NodeKind::Dir);
    }

    #[test]
    fn tar_fixture_opens_and_lists_entries() {
        let archive = open("tar/basic.tar").expect("tar opens via composed registry");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
    }

    #[test]
    fn tar_gz_opens_through_the_codec_chain() {
        for rel in ["tar/basic.tar.gz", "tar/hello.tgz"] {
            let archive =
                open(rel).unwrap_or_else(|e| panic!("{rel} opens via composed registry: {e}"));
            assert_eq!(
                names(archive.as_ref()),
                ["a.txt", "dir", "dir/b.txt"],
                "{rel}"
            );
        }
    }

    #[test]
    fn bare_gzip_is_not_an_archive() {
        let err = open("gzip/hello.txt.gz")
            .err()
            .expect("bare .gz has no file tree");
        assert!(
            matches!(err, Error::UnsupportedFormat(_)),
            "expected UnsupportedFormat, got {err:?}"
        );
    }

    #[test]
    fn unknown_bytes_are_rejected_gracefully() {
        let path = std::env::temp_dir().join("hajizip-gui-unknown.bin");
        std::fs::write(&path, b"definitely not an archive").unwrap();
        let err = compose_registry()
            .open_archive(Source::Path(path), &OpenOptions::default())
            .err()
            .expect("unknown bytes must not match any registered format");
        assert!(
            matches!(err, Error::UnsupportedFormat(_)),
            "expected UnsupportedFormat, got {err:?}"
        );
    }

    #[test]
    fn gbk_zip_lists_decoded_names() {
        let archive = open("zip/gbk.zip").expect("gbk.zip opens");
        let entries = archive.entries().unwrap();
        assert_eq!(entries.len(), 1);
        // GBK bytes C4 E3 BA C3 (你好) have no UTF-8 flag; Auto falls back to
        // GBK and decodes correctly (encoding milestone, core `478e62f`).
        assert_eq!(entries[0].path.as_str(), "你好");
    }

    #[test]
    fn encrypted_zip_lists_entries_as_encrypted() {
        let archive = open("zip/enc.zip").expect("enc.zip opens (listing only)");
        let entries = archive.entries().unwrap();
        assert_eq!(entries.len(), 1);
        assert!(entries[0].encrypted, "entry must be flagged encrypted");
    }
}
