//! The registry the GUI ships: every format `hajizip-core` implements.
//!
//! Format enumeration lives in **core**, not here: core maintains
//! [`Registry::with_all_formats`] as the canonical composition of all formats
//! it implements and keeps it up to date as formats land (see
//! `architecture.md` §4.4 and §5.1). The GUI simply references that
//! composition through [`compose_registry`], so wiring a newly added core
//! format never requires a GUI change.
//!
//! [`compose_registry`] is a thin reference to core's composition (not a
//! GUI-side enumeration). It remains as the app's single, named seam for the
//! registry it ships: a build that needs a restricted format subset can
//! compose a [`Registry`] manually (`Registry::new()` + `register_*`) instead
//! of calling it. Formats that are not registered degrade gracefully: opening
//! them yields an "unsupported format" error instead of a crash.

use hajizip_core::Registry;

/// The registry of all formats the GUI supports.
///
/// Delegates to core's canonical [`Registry::with_all_formats`], so the GUI
/// automatically supports every format core implements (ZIP, TAR, 7z
/// archives; gzip, xz codecs today) without enumerating them here.
pub fn compose_registry() -> Registry {
    Registry::with_all_formats()
}

#[cfg(test)]
mod tests {
    use super::*;
    use hajizip_core::{Archive, Error, NodeKind, OpenOptions, Source};
    use std::path::{Path, PathBuf};

    /// Repo-root `testdata/` (generated by `testdata/gen/`), shared with the
    /// core integration tests.
    fn fixture_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../testdata")
            .canonicalize()
            .expect("repo-root testdata/ must exist (generated by testdata/gen)")
    }

    fn fixture(rel: &str) -> PathBuf {
        fixture_dir().join(rel)
    }

    /// Open a fixture through the composed registry (the same path the app
    /// takes at runtime).
    fn open(rel: &str) -> hajizip_core::Result<Box<dyn Archive>> {
        compose_registry().open_archive(Source::Path(fixture(rel)), &OpenOptions::default())
    }

    fn names(archive: &dyn Archive) -> Vec<String> {
        let mut names: Vec<String> = archive
            .entries()
            .unwrap()
            .into_iter()
            .map(|e| e.path.as_str().to_string())
            .collect();
        names.sort();
        names
    }

    #[test]
    fn composed_registry_has_all_core_formats() {
        let reg = compose_registry();
        assert_eq!(reg.archive_formats().len(), 3, "zip + tar + 7z");
        assert_eq!(reg.codecs().len(), 2, "gzip + xz");
    }

    #[test]
    fn zip_fixture_opens_and_lists_entries() {
        let archive = open("zip/basic.zip").expect("zip opens via composed registry");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
        let entries = archive.entries().unwrap();
        let dir = entries.iter().find(|e| e.path.as_str() == "dir").unwrap();
        assert_eq!(dir.kind, NodeKind::Dir);
    }

    #[test]
    fn tar_fixture_opens_and_lists_entries() {
        let archive = open("tar/basic.tar").expect("tar opens via composed registry");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
    }

    #[test]
    fn tar_gz_opens_through_the_codec_chain() {
        for rel in ["tar/basic.tar.gz", "tar/hello.tgz"] {
            let archive =
                open(rel).unwrap_or_else(|e| panic!("{rel} opens via composed registry: {e}"));
            assert_eq!(
                names(archive.as_ref()),
                ["a.txt", "dir", "dir/b.txt"],
                "{rel}"
            );
        }
    }

    #[test]
    fn bare_gzip_is_not_an_archive() {
        let err = open("gzip/hello.txt.gz")
            .err()
            .expect("bare .gz has no file tree");
        assert!(
            matches!(err, Error::UnsupportedFormat(_)),
            "expected UnsupportedFormat, got {err:?}"
        );
    }

    #[test]
    fn unknown_bytes_are_rejected_gracefully() {
        let path = std::env::temp_dir().join("hajizip-gui-unknown.bin");
        std::fs::write(&path, b"definitely not an archive").unwrap();
        let err = compose_registry()
            .open_archive(Source::Path(path), &OpenOptions::default())
            .err()
            .expect("unknown bytes must not match any registered format");
        assert!(
            matches!(err, Error::UnsupportedFormat(_)),
            "expected UnsupportedFormat, got {err:?}"
        );
    }

    #[test]
    fn gbk_zip_lists_decoded_names() {
        let archive = open("zip/gbk.zip").expect("gbk.zip opens");
        let entries = archive.entries().unwrap();
        assert_eq!(entries.len(), 1);
        // GBK bytes C4 E3 BA C3 (你好) have no UTF-8 flag; Auto falls back to
        // GBK and decodes correctly (encoding milestone, core `478e62f`).
        assert_eq!(entries[0].path.as_str(), "你好");
    }

    #[test]
    fn encrypted_zip_lists_entries_as_encrypted() {
        let archive = open("zip/enc.zip").expect("enc.zip opens (listing only)");
        let entries = archive.entries().unwrap();
        assert_eq!(entries.len(), 1);
        assert!(entries[0].encrypted, "entry must be flagged encrypted");
    }

    // ---- M2 formats: 7z archive + xz codec ----

    #[test]
    fn sevenz_fixture_opens_and_lists_entries() {
        let archive = open("7z/basic.7z").expect("7z opens via composed registry");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
        let entries = archive.entries().unwrap();
        let dir = entries.iter().find(|e| e.path.as_str() == "dir").unwrap();
        assert_eq!(dir.kind, NodeKind::Dir);
    }

    #[test]
    fn sevenz_zstd_and_nonsolid_open() {
        // The ZSTD method (C-FFI zstd feature) and non-solid (random-access)
        // layouts both decode through the composed registry.
        for rel in ["7z/zstd.7z", "7z/nonsolid.7z"] {
            let archive =
                open(rel).unwrap_or_else(|e| panic!("{rel} opens via composed registry: {e}"));
            assert_eq!(
                names(archive.as_ref()),
                ["a.txt", "dir", "dir/b.txt"],
                "{rel}"
            );
        }
    }

    #[test]
    fn tar_xz_opens_through_the_codec_chain() {
        let archive = open("tar/basic.tar.xz").expect("tar.xz opens via xz→tar chain");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
    }

    #[test]
    fn bare_xz_is_not_an_archive() {
        // A standalone .xz stream decompresses to plain text, which is not an
        // archive: the registry must report UnsupportedFormat, not crash.
        let err = open("xz/hello.txt.xz")
            .err()
            .expect("bare .xz has no file tree");
        assert!(
            matches!(err, Error::UnsupportedFormat(_)),
            "expected UnsupportedFormat, got {err:?}"
        );
    }

    #[test]
    fn encrypted_7z_header_requires_password() {
        // enc.7z encrypts its header: opening without a password must report
        // PasswordRequired; the right password opens it fully.
        let err = compose_registry()
            .open_archive(Source::Path(fixture("7z/enc.7z")), &OpenOptions::default())
            .err()
            .expect("encrypted header needs a password");
        assert!(
            matches!(err, Error::PasswordRequired),
            "expected PasswordRequired, got {err:?}"
        );

        let opts = OpenOptions {
            password: Some(hajizip_core::Secret::new("secret")),
            ..OpenOptions::default()
        };
        let archive = compose_registry()
            .open_archive(Source::Path(fixture("7z/enc.7z")), &opts)
            .expect("opens with the right password");
        assert_eq!(names(archive.as_ref()), ["a.txt", "dir", "dir/b.txt"]);
    }
}
